# This is a basic workflow to help you get started with Actions

name: tag & release

# Controls when the action will run. 
on:
  push:
    tags: 
      - '*'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        
      - name: Install dotnet tool
        run: dotnet tool install -g dotnetCampus.TagToVersion

      - name: Set tag to version  
        run: |
          cd src
          dotnet TagToVersion -t ${{ github.ref }}
      
      - name: Build with dotnet
        run: |
          mkdir ${{ github.workspace }}/package
          cd src
          run: dotnet build --configuration Release --output ${{ github.workspace }}/package

      - name: Install Nuget
        uses: nuget/setup-nuget@v1
        with:        
          nuget-version: '5.x'

      - name: Add private GitHub registry to NuGet
        run: |
          nuget sources add -name github -Source https://nuget.pkg.github.com/PlayCade/index.json -Username PlayCade -Password ${{ secrets.GITHUB_TOKEN }}
      - name: Push generated package to GitHub registry
        run: |
          nuget push ${{ github.workspace }}/package/*.nupkg -Source github -SkipDuplicate
          nuget push ${{ github.workspace }}/package/*.nupkg -Source https://api.nuget.org/v3/index.json -SkipDuplicate -ApiKey ${{ secrets.NugetKey }} -NoSymbols 
